spring:
  application:
    name: rabobank-emi-calculator
  datasource:
    url: jdbc:sqlite:/usr/app/data/mydb.sqlite
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update

server:
  error:
    include-message: always